# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14e3GWzrEIehiKR0MlEuJAGwlQUGnX3n1
"""

import streamlit as st
import pandas as pd
from datetime import datetime

# Nastavení vzhledu stránky
st.set_page_config(page_title="Výpočet jízdy dodávkou", page_icon="🚐")

st.title("🚐 Evidence jízd dodávkou")
st.write("Jednoduchý nástroj pro rozpočítání nákladů mezi cestující.")

# --- VSTUPNÍ POLE ---
with st.sidebar:
    st.header("Nastavení jízdy")
    datum = st.date_input("Datum jízdy", datetime.now())
    celkova_cena = st.number_input("Celková cena za naftu/mýto (Kč)", min_value=0, value=2500, step=100)

    st.subheader("Seznam pasažérů")
    jmena_vstup = st.text_area("Zadejte jména (oddělená čárkou nebo novým řádkem)",
                               placeholder="Petr, Marek, Jana...")

# --- LOGIKA VÝPOČTU ---
# Rozdělení jmen (funguje pro čárky i nové řádky)
pasazeri = [p.strip() for p in jmena_vstup.replace('\n', ',').split(',') if p.strip()]

if pasazeri:
    pocet = len(pasazeri)
    cena_na_osobu = round(celkova_cena / pocet, 2)

    # Zobrazení výsledků v hezkých boxech
    col1, col2 = st.columns(2)
    col1.metric("Cena na osobu", f"{cena_na_osobu} Kč")
    col2.metric("Počet lidí", pocet)

    # Tabulka pro přehled
    st.subheader("Rozpis plateb")
    df = pd.DataFrame({
        "Jméno": pasazeri,
        "Částka k zaplacení": [f"{cena_na_osobu} Kč"] * pocet,
        "Zaplaceno": [False] * pocet
    })

    # Interaktivní tabulka (můžete si v ní odškrtávat)
    st.data_editor(df, use_container_width=True)

    # Tlačítko pro export (pokud si to chcete uložit)
    csv = df.to_csv(index=False).encode('utf-8')
    st.download_button("Stáhnout přehled (CSV)", csv, f"jizda_{datum}.csv", "text/csv")
else:
    st.info("👈 Do levého panelu zadejte jména pasažérů pro výpočet.")

st.divider()
st.caption("Tip: Tuto stránku si můžete uložit jako záložku v mobilu.")